# Generated by Django 4.2.17 on 2024-12-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_status', models.IntegerField(default=0)),
                ('category_order', models.IntegerField(default=1)),
                ('cat_created_date', models.DateTimeField(verbose_name='category created date')),
            ],
        ),
    ]
