# Generated by Django 4.2.17 on 2024-12-27 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(verbose_name='date published')),
                ('news_status', models.IntegerField(default=0)),
                ('url_slug', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.category')),
            ],
        ),
    ]
