# Generated by Django 4.2.17 on 2025-01-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_displaysection_newsdata_display_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='html_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsdata',
            name='news_url',
            field=models.TextField(default=''),
        ),
    ]
