# Generated by Django 4.2.17 on 2025-01-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_newsdata_html_content_newsdata_news_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registrar', models.CharField(blank=True, max_length=150, null=True)),
                ('domain_updated_date', models.DateTimeField(blank=True, null=True)),
                ('domain_created_date', models.DateTimeField(blank=True, null=True)),
                ('domain_expire_date', models.DateTimeField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpireDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registrar', models.CharField(blank=True, max_length=150, null=True)),
                ('domain_updated_date', models.DateTimeField(blank=True, null=True)),
                ('domain_created_date', models.DateTimeField(blank=True, null=True)),
                ('domain_expire_date', models.DateTimeField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KeywordDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('search_start_date', models.DateTimeField(blank=True, null=True)),
                ('search_end_date', models.DateTimeField(blank=True, null=True)),
                ('last_run_counting', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
