# Generated by Django 4.2.17 on 2025-01-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_domaindetails_expiredomain_keyworddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='display_section',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
