# Generated by Django 4.2.17 on 2025-01-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_alter_newsdata_display_section_alter_newsdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='show_type',
            field=models.IntegerField(default=1),
        ),
    ]
